name: Benchmark

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */3 * * * # Every 3 hours

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run bench.sh
        run: ./bench.sh
        shell: bash
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
