name: Code Scanning

on:
  push:
  pull_request:
  schedule:
    - cron: 0 16 * * 2 # Every Tuesday at 16:00 UTC

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize
        uses: github/codeql-action/init@v1
        with:
          languages: go
      - name: Analyze
        uses: github/codeql-action/analyze@v1
